name: CI

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: attrectotest
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Start API with Docker Compose
        run: docker-compose -f docker-compose.yml -f docker-compose.override.test.yml up -d

      - name: Wait for API to be healthy
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5001/health | grep "Healthy"; then
              echo "API is up!"
              exit 0
            fi
            echo "Waiting for API..."
            sleep 5
          done
          echo "API did not start in time" >&2
          exit 1

      - name: Run integration tests
        run: dotnet test --configuration Release --no-build

      - name: Shutdown containers
        if: always()
        run: docker-compose down -v
